<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FloVMP.Launcher</RootNamespace>
    <AssemblyName>FloVMP.Launcher</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.1.0</Version>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FloVMP.Launcher.Core\FloVMP.Launcher.Core.csproj" />
  </ItemGroup>

</Project>
