/**
 * FloV:MP — двуязычный словарь интерфейса (RU по умолчанию / EN).
 * Правило: в ветке `ru` — только русский, в ветке `en` — только английский.
 */

export type Lang = 'ru' | 'en';

const ru = {
  common: {
    getLicense: 'Купить лицензию',
    openDashboard: 'Открыть кабинет',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    docs: 'Документация',
    contactSupport: 'Написать в поддержку',
    learnMore: 'Подробнее',
    comingSoon: 'Скоро',
    online: 'Онлайн',
    offline: 'Оффлайн',
    perMonth: 'в месяц',
    perYear: 'в год',
    save: 'выгода',
    from: 'от',
    allRightsReserved: 'Все права защищены.',
    backHome: 'На главную',
  },

  nav: {
    features: 'Возможности',
    pricing: 'Тарифы',
    projects: 'Проекты',
    roadmap: 'Дорожная карта',
    docs: 'Документация',
    contact: 'Контакты',
  },

  footer: {
    tagline:
      'Независимый мультиплеерный движок нового поколения для GTA V и SaaS-платформа управления игровыми проектами.',
    colProduct: 'Продукт',
    colResources: 'Ресурсы',
    colCompany: 'Компания',
    nodeStatus: 'Узел',
    links: {
      features: 'Возможности',
      pricing: 'Тарифы и лицензии',
      dashboard: 'Личный кабинет',
      launcher: 'Сборщик лаунчера',
      docs: 'Документация',
      quickstart: 'Быстрый старт',
      api: 'Developer API',
      status: 'Статус платформы',
      projects: 'Проекты на FloV:MP',
      roadmap: 'Дорожная карта',
      contact: 'Контакты',
      terms: 'Условия использования',
      privacy: 'Политика конфиденциальности',
    },
  },

  home: {
    badge: 'SaaS-платформа и мультиплеерный движок',
    h1a: 'Своя инфраструктура',
    h1accent: 'GTA V проекта',
    h1b: 'без чужих серверов',
    sub: 'Запускайте и управляйте RP-проектами через единую панель: сетевой рантайм, лицензирование, облачная консоль серверов, телеметрия, биллинг и SDK. Полная автономия от Take-Two, RAGE:MP и alt:V backend.',
    ctaPrimary: 'Купить Lifetime-лицензию',
    ctaSecondary: 'Смотреть документацию',
    trustLine: 'Один узел = один VDS. FastDL CDN включён. Верификация ключей HMAC-SHA256.',

    statsTitle: 'Платформа в цифрах',
    stats: {
      projects: 'Активных проектов',
      servers: 'Игровых серверов',
      players: 'Игроков онлайн',
      uptime: 'Аптайм за 90 дней',
    },

    pillarsTitle: 'Три опоры платформы',
    pillars: [
      {
        n: '01',
        t: 'Автономный рантайм',
        d: 'Сервер стартует на вашем VDS и работает независимо. C# .NET 8 для логики, V8 для клиентского UI. Никаких мастер-листов и внешних зависимостей.',
      },
      {
        n: '02',
        t: 'Облачное управление',
        d: 'txAdmin-подобная веб-консоль: живой SSE-стрим логов, рестарт, kick, RCON, горячий менеджер ресурсов без падения сервера.',
      },
      {
        n: '03',
        t: 'Контроль и защита',
        d: 'Политики FloV:ID и HWID (Strict / Lenient / Disabled), анти-VPN, криптоверификация лицензий и серверный контроль всех транзакций.',
      },
    ],

    featuresTitle: 'Что входит в платформу',
    featuresSub: 'Всё для запуска и роста RP-проекта — из коробки, без сборки сторонних плагинов.',
    features: [
      { t: '3D Voice-чат', d: 'Нативный WebRTC + Opus. Пространственный звук, рации фракций, мегафоны, звуковые зоны.' },
      { t: 'Синхронизация мира', d: 'Педы, трафик, квестовые NPC и боевые противники — синхронно для всех игроков.' },
      { t: 'Облачная консоль', d: 'SSE-логи в реальном времени, RCON, рестарт и kick прямо из браузера.' },
      { t: 'Менеджер ресурсов', d: 'Старт / стоп / рестарт скриптов, карт и паков без перезапуска сервера, с контролем зависимостей.' },
      { t: 'Телеметрия 60 Hz', d: 'Тикрейт, FPS сервера, память CoreCLR, суточный график онлайна и SLA 99.98%.' },
      { t: 'Сборщик лаунчера', d: 'Брендированный Setup.exe: название, цвет, лого, FloV:Graphics (DLSS / FSR).' },
      { t: 'Верификация ключей', d: 'Формат FLV-XXXX-XXXX-XXXX, подпись HMAC-SHA256, авто-привязка IP, grace period 7 дней.' },
      { t: 'Developer API', d: 'Публичные эндпоинты статуса и игроков, вебхуки Discord / Telegram, приём донатов.' },
    ],

    quickstartTitle: 'Первый запуск сервера',
    quickstartSub: 'От архива движка до приёма игроков — один вечер по гайду.',
    quickstartPort: 'Сетевой порт',
    quickstartConsole: 'Игровая консоль',
    quickstartConsoleVal: 'клавиша F8 в клиенте + веб-консоль в кабинете',
    quickstartCmds: 'Команды администратора из коробки',
    cmds: [
      ['/o <текст>', 'глобальное оповещение всех игроков'],
      ['/pos', 'координаты игрока X, Y, Z для маппинга'],
      ['/setdim <ник> <мир>', '0 — улица, 999 — админ-тюрьма, 10000+ — дома'],
      ['/veh <модель>', 'спавн любого транспорта GTA V'],
      ['/stats', 'сводка об игроке, пинге и железе'],
    ],
    quickstartBans: 'Многоуровневая система банов',
    bans: [
      ['/ban', 'бан аккаунта'],
      ['/banip', 'бан по IP'],
      ['/bansc', 'бан лицензии Rockstar Social Club'],
      ['/hwidban', 'бан по железу ПК (FloV:ID)'],
      ['/hardban', 'тотальный: Account + IP + SC + HWID + MAC'],
      ['/unban', 'универсальная разблокировка'],
    ],

    ownershipTitle: 'Полный контроль над сервером',
    ownershipSub:
      'FloV:MP не навязывает лор и не ставит скрытых блокировок. Любая карта — реальная Москва, Дикий Запад XIX века или кастомные острова.',
    ownership: [
      { t: '«Чистый холст» — Blank C# SDK', d: 'Пустой проект на C# .NET 8 для уникальных механик со своей архитектурой.' },
      { t: '«RP Стартер» — готовая база', d: 'Экономика, админ-система, инвентарь и дименшены интерьеров из коробки.' },
    ],

    projectsTitle: 'Проекты уже на FloV:MP',
    projectsSub: 'Каждый проект объединяет несколько серверов: production, development, test.',
    projectsCta: 'Все проекты',

    ctaTitle: 'Подключите свой RP-сервер сегодня',
    ctaSub: 'Расскажем, как перенести проект с RAGE:MP или FiveM, и поможем с первым запуском.',
  },

  features: {
    title: 'Возможности платформы',
    sub: 'Подробно о том, из чего состоит FloV:MP: сетевой движок, облачное управление, безопасность и инструменты разработчика.',
    groups: [
      {
        t: 'Сетевой движок',
        items: [
          ['Автономный рантайм', 'altv-server v16.4.39 (unhooked). Весь сетевой стек — EntityStreamer, SyncSend/Receive, NetworkWorker — поднимается локально без обращения к бэкенду alt:V.'],
          ['C# .NET 8 гейммод', 'CoreCLR-модуль, полноценный доступ к API движка, hot-reload ресурсов, типобезопасный SDK (NuGet).'],
          ['Клиент NUI на JS/TS', 'HUD, меню, камеры и интерфейсы на HTML/CSS/JS. Переиспользование наработок с RAGE:MP и FiveM.'],
          ['Синхронизация мира', 'Живой город с ботами, квестовые и боевые NPC, синхронный трафик, погода и время.'],
        ],
      },
      {
        t: 'Облачное управление',
        items: [
          ['txAdmin Cloud Console', 'Двусторонний агент на игровом сервере. Живой SSE-стрим консоли в браузер, RCON, рестарт, kick, broadcast.'],
          ['Dynamic Resource Manager', 'Старт / стоп / рестарт отдельных скриптов, карт, паков машин и NUI без перезапуска сервера. Граф зависимостей.'],
          ['Watchdog и краши', 'Супервизор зависаний > 15 с, дамп стека CoreCLR, авторестарт (лимит 5 / час), лог аварийных завершений.'],
          ['Среды проекта', 'Production, Development, Test Sandbox — раздельные лицензии-привязки и телеметрия.'],
        ],
      },
      {
        t: 'Безопасность',
        items: [
          ['FloV:ID и HWID', 'Аппаратные идентификаторы ПК. Политики Strict / Lenient / Disabled, лимит аккаунтов на одно железо.'],
          ['Анти-VPN', 'Определение и блокировка VPN / прокси на входе, белые списки.'],
          ['Верификация лицензий', 'Формат FLV-XXXX-XXXX-XXXX, ответ подписан HMAC-SHA256, авто-привязка первого внешнего IP.'],
          ['Grace period', 'Сервер кэширует лицензию локально и работает до 7 дней при недоступности портала.'],
        ],
      },
      {
        t: 'Инструменты разработчика',
        items: [
          ['Launcher Builder', 'Брендированный Setup.exe: название, HEX-цвет, лого, FloV:Graphics (DLSS / FSR, детект GPU).'],
          ['Public Developer API', '/status, /players, /donate (проверка X-Signature HMAC) — для мониторингов и внешних сайтов.'],
          ['Вебхуки', 'Discord Rich Embeds и Telegram Bot API: краши, пики нагрузки, восстановление, срабатывание HWID-политики.'],
          ['SDK и FastDL', 'Ядра Linux/Win, C# SDK, Asset Packer CLI, сниппеты кода, гигабитная раздача контента по HTTP/2.'],
        ],
      },
    ],
  },

  pricing: {
    title: 'Тарифы и лицензии',
    sub: 'Стартовая лицензия — бесплатно. Скидки при оплате за 6 или 12 месяцев. Партнёрская программа — 20% пожизненно.',
    periodMonth: '1 месяц',
    periodHalf: '6 месяцев',
    periodYear: '1 год',
    popular: 'Популярный выбор',
    cta: 'Выбрать тариф',
    ctaFree: 'Начать бесплатно',
    plans: [
      {
        id: 'starter',
        name: 'Starter',
        tagline: 'Для разработки и теста нового сервера',
        priceMonth: '0 ₽',
        note: '30 дней',
        features: ['До 128 игроков', 'Автономные бинарники движка', 'C# Gamemode SDK', 'Привязка 1 IP', 'Облачная консоль (read-only)'],
      },
      {
        id: 'pro',
        name: 'Pro',
        tagline: 'Для запуска полноценного RP-проекта',
        priceMonth: '14 900 ₽',
        note: 'за проект',
        features: ['До 512 игроков', 'Готовая база «RP Стартер»', '3D Voice + синхронизация NPC', 'txAdmin Cloud + Resource Manager', 'FloV:ID / HWID политики', 'Вебхуки Discord / Telegram'],
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        tagline: 'Для крупных проектов и франшиз',
        priceMonth: '49 000 ₽',
        note: 'за проект',
        features: ['1500+ игроков', 'Брендированный лаунчер', 'Миграция с RAGE:MP / FiveM «под ключ»', 'Выделенная поддержка · SLA 99.9%', 'Приоритет в дорожной карте'],
      },
    ],
    faqTitle: 'Вопросы по биллингу',
    faq: [
      ['Как работает Lifetime-лицензия?', 'Одна лицензия закрепляется за проектом навсегда. Внутри проекта — сколько угодно серверов (production / dev / test), общий SDK и API-ключи.'],
      ['Что с продлением?', 'Тарифы Pro и Enterprise — подписка на проект. Автопродление можно включить или выключить в кабинете. Скидка −15% за 6 месяцев, −30% за год.'],
      ['Как оплатить?', 'Карта, СБП QR или USDT. Активация лицензии — моментальная после подтверждения оплаты.'],
      ['Партнёрская программа?', '20% от платежей приглашённых проектов — пожизненно. Промокод и статистика — в разделе Settings кабинета.'],
    ],
  },

  projects: {
    title: 'Проекты на FloV:MP',
    sub: 'Витрина RP-проектов, развёрнутых поверх платформы. Публичный статус обновляется в реальном времени.',
    thServers: 'серверов',
    thOnline: 'онлайн',
    thPeak: 'пик',
    visit: 'Перейти',
  },

  roadmap: {
    title: 'Дорожная карта',
    sub: 'Ближайшие вехи развития движка и SaaS-платформы. Приоритеты Enterprise-клиентов учитываются в первую очередь.',
    statusDone: 'Готово',
    statusActive: 'В работе',
    statusPlanned: 'Запланировано',
    items: [
      { q: 'Q3 2026', t: 'Автономный рантайм', s: 'done', d: 'Отвязка бинарников alt:V, локальный старт сетевого стека, FastDL CDN, верификация ключей HMAC.' },
      { q: 'Q3 2026', t: 'SaaS-портал MVP', s: 'done', d: 'Лицензии, среды, биллинг, телеметрия, сборщик лаунчера, публичный API.' },
      { q: 'Q4 2026', t: 'txAdmin Cloud Console', s: 'active', d: 'Двусторонний агент, SSE-стрим логов, RCON, менеджер ресурсов, watchdog.' },
      { q: 'Q4 2026', t: 'FloV:ID / HWID', s: 'active', d: 'Аппаратные идентификаторы, политики Strict / Lenient / Disabled, анти-VPN.' },
      { q: 'Q1 2027', t: '2FA и RBAC', s: 'planned', d: 'TOTP, роли Owner / Project Lead / Developer, аудит действий команды.' },
      { q: 'Q1 2027', t: 'Нагрузочный тест 3000+', s: 'planned', d: 'Стресс-тест сетевого стека и стриминга на тысячах игроков.' },
      { q: 'Q2 2027', t: 'Автодеплой и хостинг', s: 'planned', d: 'Деплой из ветки в один клик, интеграция с REDL Hosting, снапшоты.' },
    ],
  },

  contact: {
    title: 'Контакты',
    sub: 'Расскажите про проект — предложим тариф, поможем с переносом и первым запуском.',
    tgTitle: 'Telegram',
    tgDesc: 'Быстрые ответы по будням, обсуждение переноса и техвопросы.',
    dsTitle: 'Discord',
    dsDesc: 'Комьюнити разработчиков, анонсы обновлений и статус платформы.',
    formTitle: 'Оставить заявку',
    formName: 'Имя или ник',
    formContact: 'Telegram / Email',
    formProject: 'Про проект',
    formSubmit: 'Отправить заявку',
    formNote: 'Это демонстрационная форма — отправьте сообщение в Telegram для реального ответа.',
  },

  dash: {
    hello: 'Здравствуйте',
    roleAdmin: 'Администратор',
    roleClient: 'Клиент SaaS',
    headerSub: 'Лицензии, телеметрия VDS, биллинг и брендированный лаунчер FloV:MP',
    newLicense: 'Новая лицензия',
    loading: 'Загрузка панели управления FloV:MP…',
    refresh: 'Обновить',
    cancel: 'Отмена',
    tabs: {
      projects: 'Проекты и серверы',
      console: 'txAdmin консоль',
      troubleshoot: 'AI диагностика',
      overview: 'Ключи и статус',
      telemetry: 'Телеметрия VDS',
      sdk: 'Загрузки и SDK',
      builder: 'Сборщик лаунчера',
      billing: 'Счета и биллинг',
      affiliate: 'Партнёрка (20%)',
      analytics: 'Аналитика',
      watchdog: 'Watchdog и краши',
      logs: 'Логи',
      api: 'API и вебхуки',
      settings: 'Настройки',
    },
    buildStages: ['Генерация конфигурации…', 'Упаковка Electron + Native Bridge…', 'Подписание EXE…', 'Готово'],
    toast: {
      errLoad: 'Не удалось загрузить данные кабинета',
      errLoadServers: 'Не удалось загрузить серверы проекта',
      errSave: 'Ошибка сохранения',
      settingsSaved: 'Настройки проекта и Webhook сохранены',
      errSend: 'Ошибка отправки',
      alertsSent: 'Тестовые алерты отправлены',
      errResource: 'Ошибка управления ресурсом',
      sseOff: 'Живой SSE-стрим консоли отключён',
      sseOn: 'Живой SSE-стрим консоли активирован',
      sseErr: 'Не удалось подключиться к SSE-потоку',
      errCreateProj: 'Ошибка создания проекта',
      projCreated: 'Новый проект создан',
      errCmd: 'Ошибка отправки команды',
      pasteLogs: 'Вставьте фрагмент логов сервера для анализа',
      errAnalyze: 'Ошибка анализа логов',
      aiDone: 'AI-диагностика завершена',
      errBindIp: 'Ошибка привязки IP',
      ipSaved: 'IP-адрес сохранён',
      errCreateLic: 'Ошибка создания лицензии',
      licActivated: 'Лицензия активирована',
      errPay: 'Ошибка оплаты',
      payConfirmed: 'Оплата подтверждена',
      errInvoice: 'Ошибка выставления счёта',
      hbRecorded: 'Heartbeat-пакет записан',
      errTelemetry: 'Ошибка записи телеметрии',
      needActiveLic: 'Для сборки нужна активная лицензия',
      errBuild: 'Ошибка сборки лаунчера',
      launcherBuilt: 'Кастомный лаунчер собран',
      consoleCleared: 'Консоль очищена',
      err: 'Ошибка',
      cmdToAgent: 'Команда отправлена агенту',
      cmdQueued: 'Команда поставлена в очередь',
      invoiceIssued: 'Счёт выставлен',
      twoFaOn: 'Двухфакторная аутентификация включена',
      twoFaOff: 'Двухфакторная аутентификация отключена',
      twoFaErr: 'Неверный код подтверждения',
      accSaved: 'Данные аккаунта сохранены',
    },
    proj: {
      title: 'Проекты экосистемы FloV:MP',
      hierarchy: 'Иерархия: Аккаунт → Проект (лицензия) → Игровые серверы (Prod / Dev / Test)',
      create: 'Создать проект',
      slots: 'слотов',
      activeProject: 'Активный проект',
      plan: 'Тариф',
      limit: 'Лимит',
      copyLicenseKey: 'Скопировать License Key',
      copyAgentKey: 'Скопировать Agent API Key',
      settingsWebhook: 'Настройки и Webhook',
      envTitle: 'Серверные среды (Environments)',
      envSub: 'txAdmin Cloud агент на каждом узле слушает команды и отправляет телеметрию',
      serversCount: 'Серверов',
      noServers: 'В этом проекте ещё нет запущенных серверов.',
      agentActive: 'Agent Active',
      slotsShort: 'Слоты',
      protocol: 'Протокол',
      agent: 'Агент',
      restart: 'Перезапуск',
      stop: 'Остановить',
      announce: 'Анонс игрокам',
      resTitle: 'Управление ресурсами сервера (Resource Manager)',
      resSub: 'Запуск, остановка и перезапуск скриптов, карт и транспорта на лету без перезагрузки узла',
      resReload: 'Обновить ресурсы',
      thResource: 'Ресурс',
      thType: 'Тип',
      thVersion: 'Версия',
      thStatus: 'Статус',
      thControl: 'Управление',
      running: 'Работает',
      stopped: 'Остановлен',
      resRestart: 'Перезапустить ресурс',
      resStop: 'Остановить ресурс',
      resStart: 'Запустить ресурс',
    },
    console: {
      title: 'txAdmin Cloud Web Console',
      sub: 'Прямой двухсторонний канал управления сервером FloV:MP через RemoteServerAgent',
      agentConnected: 'Agent Connected (UDP 7788)',
      sseTitle: 'Реальное время без задержек по Server-Sent Events',
      sseOn: 'SSE активен',
      sseOff: 'Включить SSE',
      clear: 'Очистить',
      chipReboot: 'Перезагрузка с анонсом',
      chipRebootCmd: 'broadcast Внимание: перезагрузка через 5 минут!',
      chipStatus: 'Запросить статус игроков',
      chipGc: 'Принудительный GC',
      chipBattleye: 'Проверить BattlEye',
      placeholder: 'broadcast [текст], restart, stop или команда сервера…',
      send: 'Отправить',
    },
    ai: {
      title: 'FloV:AI — диагностика и автоисправление сбоев',
      sub: 'Анализ логов запуска сервера, сбоев CoreCLR (.NET), портов UDP 7788, BattlEye и resource.toml',
      presetsLabel: 'Пресеты типовых сбоев для быстрой проверки:',
      pCoreclr: 'Сбой CoreCLR (.NET)',
      pUdp: 'Блокировка UDP 7788',
      pBin: 'Отсутствие .bin файлов',
      pToml: 'Ошибка resource.toml',
      inputLabel: 'Фрагмент лога ошибки altv-server или исключения C#',
      inputPlaceholder: 'Вставьте сюда текст ошибки (например: FATAL [CoreCLR] System.Exception: …)',
      analyzing: 'Нейроанализ логов…',
      diagnose: 'Диагностировать ошибку',
      category: 'Категория',
      cause: 'Причина инцидента:',
      solution: 'Пошаговое решение проблемы:',
      docs: 'Документация',
    },
    overview: {
      quickStart: 'Быстрый старт проекта',
      stepAccount: 'Аккаунт создан',
      stepLicense: 'Лицензия активна',
      stepLicenseNo: 'Не создана',
      stepPlan: 'Тариф',
      stepIp: 'IP сервера привязан',
      stepIpNo: 'Требуется привязать',
      stepNode: 'Сетевой узел онлайн',
      yourLicenses: 'Ваши лицензии',
      licSub: 'Каждый ключ привязывается к IPv4 игрового сервера',
      total: 'Всего',
      noLicenses: 'У вас пока нет активных лицензий',
      createFirst: 'Создать первую лицензию',
      planLabel: 'Тариф',
      active: 'Активна',
      suspended: 'Приостановлена',
      hideKey: 'Скрыть ключ',
      showKey: 'Показать ключ',
      copyKey: 'Скопировать ключ',
      ipAny: 'любой (0.0.0.0)',
      slotsShort: 'Слоты',
      expires: 'Истекает',
      configureIp: 'Настроить IP',
      server: 'Сервер',
      tomlTitle: 'Прописка ключа в',
      tomlStep1: 'Скачайте архив движка кнопкой «Сервер» на карточке лицензии.',
      tomlStep2: 'В файле',
      tomlStep2b: 'укажите блок:',
      tomlStep3a: 'Запустите',
      tomlStep3b: '— узел пройдёт онлайн-верификацию и начнёт приём игроков.',
    },
    tele: {
      title: 'Мониторинг игрового узла',
      testHeartbeat: 'Тестовый heartbeat',
      tickFoot: 'Синхронизация 16.6 ms',
      fpsFoot: 'Физика без просадок',
      ramFoot: 'ОЗУ оптимизировано',
      playersLabel: 'Игроки онлайн',
      playersFoot: 'Слоты активны',
      curveTitle: 'Суточная динамика онлайна игроков (24h Activity)',
      curveSub: 'Почасовая активность серверов проекта с расчётом пикового онлайна и аптайма SLA',
      peak: 'Пик',
      peakVal: '184 игрока',
      night: 'Ночь',
      morning: 'Утро',
      day: 'День',
      prime: 'Прайм-тайм',
      historyTitle: 'История пакетов телеметрии (последние 30)',
      noPackets: 'Нет записанных пакетов. Нажмите «Тестовый heartbeat», чтобы отправить пакет со стенда.',
      thTime: 'Время',
      thNodeIp: 'IP узла',
      thOnline: 'Онлайн',
      thRam: 'ОЗУ',
    },
    sdk: {
      title: 'Дистрибутивы и SDK FloV:MP',
      sub: 'Автономный мультиплеерный рантайм, модули CoreCLR, библиотека C# SDK и утилиты FastDL',
      items: [
        ['FloV:MP Server Core (Linux)', 'Автономный рантайм для VDS Ubuntu 22.04 / Debian 12. Включает coreclr-module, BattlEye и UDP-стример.', 'Скачать tar.gz'],
        ['FloV:MP Server Core (Windows)', 'Локальный сервер для разработки под Windows 10/11/Server 2022. Полная изоляция от внешних бэкендов.', 'Скачать zip'],
        ['FloVMP.Core C# .NET 8 SDK', 'Пакет C# API: EntityStreamer, RemoteServerAgent, FactionEngine, LicensingService для создания гейммодов.', 'Скачать SDK'],
        ['FloV:MP Asset Packer (CLI)', 'Консольная утилита шифрования клиентских ресурсов и автогенерации манифестов FastDL перед релизом.', 'Скачать Packer'],
        ['Electron Launcher Template', 'Исходный код брендированного лаунчера на Chromium UI + C# Native Bridge с аппаратным ускорением.', 'Скачать шаблон'],
        ['Примеры гейммодов (Templates)', 'Готовые шаблоны ролевых проектов: RP-основа, дрифт-сервер, DM-арена с полной C# типизацией.', 'Скачать примеры'],
      ] as [string, string, string][],
    },
    builder: {
      title: 'Сборщик кастомного лаунчера',
      sub: 'Компиляция установщика под бренд и IP проекта',
      projectName: 'Название проекта',
      hexColor: 'Фирменный HEX-цвет',
      serverIp: 'IP сервера',
      udpPort: 'UDP порт',
      compiling: 'Компиляция…',
      compile: 'Скомпилировать лаунчер проекта',
      statusTitle: 'Статус сборщика',
      built: 'Лаунчер собран',
      bProject: 'Проект',
      bColor: 'Цвет',
      bEndpoint: 'Эндпоинт',
      bLicense: 'Лицензия',
      download: 'Скачать',
      waiting: 'Ожидание запуска сборки',
      waitingSub: 'Укажите параметры слева и нажмите «Скомпилировать». Билдер упакует Electron + C# Native Bridge и FastDL-манифест.',
      feat: [
        'Аппаратное ускорение Chromium UI (blur / shadows)',
        'Прямой коннектор C# .NET 8 (FloVMP.Connect)',
        'Вшитый FastDL-кэш с CDN VDS',
      ],
    },
    billing: {
      title: 'Счета и управление подпиской',
      sub: 'Счета формируются автоматически, продление лицензий — моментальное',
      issue: 'Выставить счёт на продление',
      historyTitle: 'История выставленных счетов',
      noInvoices: 'Счетов пока нет.',
      issueShort: 'Выставить счёт',
      thNo: '№',
      thPlan: 'Тариф',
      thAmount: 'Сумма',
      thMethod: 'Метод',
      thCreated: 'Создан',
      thStatus: 'Статус',
      thAction: 'Действие',
      paid: 'Оплачен',
      pending: 'Ожидает оплаты',
      closed: 'Закрыт',
      pay: 'Оплатить',
    },
    aff: {
      program: 'Партнёрская программа',
      earn: 'Зарабатывайте 20% от оплат серверов',
      descA: 'Рекомендуйте FloV:MP владельцам GTA V RP-серверов. Вы получаете',
      descB: '20% пожизненно',
      descC: 'с каждого продления лицензии приглашённого проекта. Приглашённый проект получает скидку',
      descD: '10%',
      copied: 'Скопировано',
      copy: 'Копировать',
      invited: 'Приглашено проектов',
      activeRefs: 'Активные рефералы',
      earned: 'Начислено вознаграждений',
      available: 'Доступно к выводу',
      percent: 'Процент отчислений',
      lifetime: 'Пожизненно со всех платежей',
    },
    modal: {
      bindIpTitle: 'Привязка IP-адреса сервера',
      bindIpDesc: 'Публичный IPv4-адрес VDS, на котором развёрнут игровой сервер',
      serverName: 'Название сервера',
      ipv4: 'IPv4-адрес',
      saveBinding: 'Сохранить привязку',
      newLicTitle: 'Оформление новой лицензии',
      newLicDesc: 'Выберите тариф под масштабы вашего игрового проекта',
      indie: 'Инди',
      free: 'Бесплатно',
      yourServerName: 'Название вашего сервера',
      ipLater: 'IP сервера (можно указать позже)',
      activateLic: 'Активировать лицензию',
      newProjTitle: 'Создание нового проекта',
      newProjDesc: 'Проект объединяет единую лицензию и несколько сред: Production, Development, Test',
      slugLabel: 'Slug-идентификатор (URL проекта)',
      settingsTitle: 'Настройки проекта и Webhooks',
      settingsDesc: 'Политика безопасности FloV:ID, пропуск обходников HWID и алерты в Discord / Telegram',
      hwidPolicy: 'Политика безопасности FloV:ID и HWID',
      hwidStrict: 'Строгий (Strict)',
      hwidStrictDesc: 'Блокировка забаненных HWID',
      hwidLenient: 'Мягкий (Lenient)',
      hwidLenientDesc: 'Вход разрешён с аудитом',
      hwidDisabled: 'Выключен (Disabled)',
      hwidDisabledDesc: 'Пускать всех без ограничений',
      maxAccs: 'Максимум аккаунтов на 1 HWID',
      allowVpn: 'Разрешать игрокам вход через VPN / Proxy',
      alertsTitle: 'Оповещения в Discord и Telegram',
      alertsSub: 'Автоматическая отправка уведомлений о падении сервера, сбоях и превышении нагрузки',
      enabled: 'Включены',
      test: 'Тест',
      saveProjectParams: 'Сохранить параметры проекта',
      invoiceTitle: 'Выставление счёта на оплату',
      invoiceDesc: 'Выберите тариф, период и способ оплаты',
      planLabel: 'Тарифный план',
      periodLabel: 'Период оплаты',
      methodLabel: 'Способ оплаты',
      pMonth: '1 месяц',
      pHalf: '6 мес · −15%',
      pYear: '1 год · −30%',
      mCard: 'Карта',
      mSbp: 'СБП QR',
      issueInvoice: 'Выставить счёт',
    },
    wd: {
      title: 'Watchdog и аварийные завершения',
      sub: 'Супервизор зависаний главного потока и автоматический перезапуск CoreCLR',
      threshold: 'Порог зависания',
      thresholdVal: '15.0 с',
      restarts: 'Авторестартов за час',
      restartsVal: '2 / 5',
      uptime: 'Аптайм супервизора',
      uptimeVal: '30 дней',
      crashLog: 'Логи аварийных завершений',
      thTime: 'Время',
      thServer: 'Сервер',
      thReason: 'Причина',
      thRestarted: 'Рестарт',
      ok: 'Восстановлен',
      failed: 'Не поднялся',
      dumpTitle: 'Дамп стека CoreCLR — последний краш',
      rows: [
        ['2026-09-06 09:12:44', 'florida-prod-02', 'CoreCLR SIGSEGV в econ_core.PayrollTick', true],
        ['2026-09-05 22:41:03', 'florida-dev', 'Watchdog: зависание главного потока 18.3 с', true],
        ['2026-09-04 03:07:19', 'florida-prod-01', 'OOM — heap 7.8 GB / 8 GB', true],
      ] as [string, string, string, boolean][],
    },
    logs: {
      title: 'Системные логи',
      sub: 'История событий проекта — поиск и фильтр по уровню',
      search: 'Поиск по сообщению или источнику',
      notFound: 'Ничего не найдено',
      rows: [
        ['2026-09-06 12:41:07', 'INFO', 'network', 'player connected id=41 «Mikhail_D» ip=***.***.14.2'],
        ['2026-09-06 12:41:05', 'INFO', 'license', 'license FLV-•••• verified · slots 1500 · sig ok'],
        ['2026-09-06 12:41:04', 'OK', 'fastdl', 'FastDL manifest verified (2 184 files, 6.1 GB)'],
        ['2026-09-06 12:40:58', 'WARN', 'gamemode', 'tick spike 22ms on resource econ_core'],
        ['2026-09-06 12:40:32', 'INFO', 'api', 'API key rotated · project florida-v · by Anna K.'],
        ['2026-09-06 12:39:11', 'ERROR', 'voice', 'webrtc renegotiation failed for peer 88 — retry scheduled'],
        ['2026-09-06 12:38:00', 'INFO', 'agent', 'deploy florida-prod-01 → v16.4.39 completed in 41s'],
        ['2026-09-06 12:20:05', 'OK', 'db', 'MariaDB pool healthy · 12/50 connections'],
        ['2026-09-06 12:04:49', 'WARN', 'monitoring', 'CPU 82% on florida-prod-01 for 3m — alert sent'],
        ['2026-09-06 09:12:44', 'CRASH', 'watchdog', 'CoreCLR SIGSEGV — core dumped, autorestart ok'],
      ] as [string, string, string, string][],
    },
    an: {
      title: 'Аналитика проекта и серверов',
      sub: 'Онлайн, нагрузка и сеть за последние 24 часа. Данные телеметрии игровых узлов.',
      peak: 'Пик онлайна',
      peakVal: '2 310',
      avg: 'Средний онлайн',
      avgVal: '1 460',
      sla: 'Аптайм · SLA',
      slaVal: '99.98%',
      cOnline: 'Онлайн игроков',
      cCpu: 'CPU нагрузка',
      cRam: 'RAM использование',
      cNet: 'Сетевой трафик',
      gCpu: 'CPU сейчас',
      gRam: 'RAM сейчас',
      gNet: 'Сеть',
      gFoot: 'среднее по серверам проекта',
      h24: '24ч',
    },
    api: {
      title: 'API и вебхуки',
      sub: 'Ключи доступа, публичные эндпоинты и алерты в Discord / Telegram',
      baseUrl: 'Base URL проекта',
      agentKey: 'Agent API Key',
      keyHint: 'Ключ агента RemoteServerAgent на игровом сервере. Не публикуйте его.',
      rotate: 'Ротировать',
      rotating: 'Ротация…',
      rotated: 'Agent API Key обновлён',
      show: 'показать',
      hide: 'скрыть',
      copy: 'Копировать',
      copied: 'Скопировано',
      publicTitle: 'Публичные эндпоинты (Developer API)',
      publicSub: 'Для мониторингов, сайтов проекта и донат-магазина. HMAC-подпись в заголовке X-Signature для /donate.',
      epStatus: 'онлайн, игроки, версия, пинг, аптайм',
      epPlayers: 'список игроков сервера',
      epDonate: 'приём донатов с внешних сайтов (проверка X-Signature)',
      webhooksTitle: 'Вебхуки Discord / Telegram',
      webhooksSub: 'Настраиваются в модалке «Настройки и Webhook» на вкладке «Проекты и серверы».',
      whDiscord: 'Discord Webhook',
      whTelegram: 'Telegram Bot',
      whOn: 'подключён',
      whOff: 'не настроен',
      openSettings: 'Открыть настройки проекта',
      noProject: 'Сначала выберите проект на вкладке «Проекты и серверы».',
    },
    sec: {
      accountTitle: 'Аккаунт',
      name: 'Имя',
      email: 'Email',
      telegram: 'Telegram',
      save: 'Сохранить',
      twoFaTitle: 'Двухфакторная аутентификация (TOTP)',
      twoFaOnDesc: 'Включена · при входе запрашивается код из приложения',
      twoFaOffDesc: 'Не подключена — рекомендуем включить для защиты аккаунта',
      enable: 'Подключить 2FA',
      disable: 'Отключить 2FA',
      setupHint: 'Добавьте ключ в приложение-аутентификатор (Google Authenticator, Authy, 1Password), затем введите код.',
      secretLabel: 'Ключ (ручной ввод)',
      uriLabel: 'otpauth-ссылка',
      codeLabel: 'Код из приложения',
      confirm: 'Подтвердить и включить',
      cancel: 'Отмена',
      refTitle: 'Реферальная программа · 20% RevShare',
      refCode: 'Ваш промокод',
      copied: 'Скопировано',
      copy: 'Копировать',
      refInvited: 'Приглашено',
      refEarned: 'Начислено',
      refShare: 'Доля',
      sessionsTitle: 'Активные сессии',
      sessionCurrent: 'эта',
      sessionRevoke: 'Выйти',
      sessions: [
        ['Chrome · Windows 11', '188.127.•.14', 'Москва, RU', 'сейчас', true],
        ['FloV:MP Launcher', '188.127.•.14', 'Москва, RU', '2 ч назад', false],
        ['Safari · iPhone', '31.173.•.88', 'Казань, RU', 'вчера', false],
      ] as [string, string, string, string, boolean][],
    },
  },

  adm: {
    accessDenied: 'Доступ запрещён: требуется аккаунт администратора',
    loadFailed: 'Не удалось загрузить данные платформы',
    err: 'Ошибка',
    loading: 'Загрузка панели администратора…',
    refresh: 'Обновить',
    mRevenue: 'Общий доход',
    mServers: 'Всего серверов',
    mLicenses: 'Активные лицензии',
    mClients: 'Всего клиентов',
    headerTitle: 'Управление платформой и реестром серверов',
    headerSub: 'Контроль лицензий, клиентов, платежей и статусов узлов',
    allLicenses: 'Все выданные лицензии',
    thServerProject: 'Сервер / проект',
    thKey: 'Ключ',
    thPlan: 'Тариф',
    thStatus: 'Статус',
    thExpires: 'Истекает',
    thActions: 'Действия',
    active: 'Активна',
    suspended: 'Приостановлена',
    freeze: 'Заморозить',
    unfreeze: 'Разморозить',
    clients: 'Клиенты',
    thLogin: 'Логин',
    thRole: 'Роль',
    thCreated: 'Создан',
    txRegistry: 'Реестр транзакций',
    thClient: 'Клиент',
    thAmount: 'Сумма',
    thDate: 'Дата',
    paid: 'Оплачен',
    pending: 'Ожидает',
    noTx: 'Транзакций пока нет.',
    logNote: 'Все операции журналируются',
  },

  auth: {
    loginTitle: 'Вход в кабинет',
    loginSub: 'Управление лицензиями, серверами и биллингом FloV:MP',
    registerTitle: 'Регистрация в FloV:MP',
    registerSub: 'Бесплатная лицензия Starter на 128 слотов — сразу после создания аккаунта',
    email: 'Email',
    password: 'Пароль',
    passwordHint: 'Минимум 6 символов',
    username: 'Логин',
    telegram: 'Telegram',
    signIn: 'Войти в аккаунт',
    signInBusy: 'Входим…',
    createAccount: 'Создать аккаунт',
    createBusy: 'Создаём аккаунт…',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    toRegister: 'Зарегистрироваться',
    toLogin: 'Войти',
    freeLicenseNote: 'При регистрации автоматически создаётся лицензия Starter (128 слотов, 30 дней).',
    errGeneric: 'Что-то пошло не так. Попробуйте ещё раз.',
  },

  docs: {
    title: 'Документация и API',
    sub: 'Верификация лицензий, телеметрия, облачный агент и настройка FastDL. Интерактивные примеры отправляют реальные запросы к API портала.',
    navQuickstart: 'Быстрый старт',
    navVerify: 'Верификация лицензии',
    navAgent: 'Облачный агент',
    navTelemetry: 'Телеметрия',
    navSdk: 'SDK и сниппеты',
    navFastdl: 'FastDL (Nginx)',

    quickstartTitle: 'Первый запуск сервера',
    quickstartLead: 'От распаковки архива движка до приёма игроков — по шагам.',
    steps: [
      ['1. Дистрибутив', 'Скачайте серверное ядро для Linux в кабинете и распакуйте на VDS. Скопируйте .bin-файлы движка в рабочую папку.'],
      ['2. server.toml', 'Пропишите лицензионный ключ FLV-XXXX-XXXX-XXXX, публичный IPv4 сервера и URL FastDL CDN.'],
      ['3. Порт', 'Откройте UDP 7788 (протокол alt:V нового поколения, автономный старт).'],
      ['4. Запуск', 'Запустите ./start.sh — узел проходит онлайн-верификацию по HMAC и открывает приём игроков.'],
      ['5. Консоль', 'Клавиша F8 в клиенте открывает игровую консоль; веб-консоль доступна в кабинете (SSE-стрим).'],
    ],
    reqTitle: 'Тело запроса',
    resTitle: 'Ответ API',
    runVerify: 'Выполнить тестовую верификацию',
    running: 'Отправка запроса…',
    verifyHint: '// Нажмите кнопку — здесь появится JSON с подписью HMAC-SHA256',
    agentHint: '// Connect — раскроется живой поток консоли (демо)',
    verifyDesc: 'Эндпоинт, к которому сервер обращается при старте и каждые 15 минут. Проверяет статус ключа, привязку IPv4 и подписывает ответ HMAC-SHA256.',
    agentDesc: 'Двусторонний агент на игровом сервере опрашивает очередь команд и отдаёт вывод консоли в браузер через Server-Sent Events. Команды: restart, stop, broadcast, kick_all, resource_start / stop / restart, execute.',
    telemetryDesc: 'Сервер отправляет пакет каждую минуту: онлайн, тикрейт, FPS, память CoreCLR. История последних 30 пакетов строит графики в разделе Analytics.',
    sdkDesc: 'Готовые сниппеты для серверного гейммода AltV.Net, Node.js и конфигурации FastDL.',
    fastdlDesc: 'Раздача клиентских файлов на скорости гигабитного порта через HTTP/2. Игровой UDP-канал остаётся разгруженным.',
    fastdlFacts: [
      ['Cache-Control', 'immutable, 30 дней'],
      ['Протокол', 'HTTP/2 + sendfile'],
      ['Нагрузка на UDP', '0% — канал разгружен'],
    ],
  },

  notFound: {
    title: 'Страница не найдена',
    sub: 'Такой страницы нет или она была перемещена.',
  },
};

const en: typeof ru = {
  common: {
    getLicense: 'Get a license',
    openDashboard: 'Open dashboard',
    login: 'Log in',
    register: 'Sign up',
    logout: 'Log out',
    docs: 'Documentation',
    contactSupport: 'Contact support',
    learnMore: 'Learn more',
    comingSoon: 'Soon',
    online: 'Online',
    offline: 'Offline',
    perMonth: 'per month',
    perYear: 'per year',
    save: 'save',
    from: 'from',
    allRightsReserved: 'All rights reserved.',
    backHome: 'Back home',
  },

  nav: {
    features: 'Features',
    pricing: 'Pricing',
    projects: 'Projects',
    roadmap: 'Roadmap',
    docs: 'Docs',
    contact: 'Contact',
  },

  footer: {
    tagline:
      'Next-generation independent multiplayer engine for GTA V and a SaaS platform for managing game projects.',
    colProduct: 'Product',
    colResources: 'Resources',
    colCompany: 'Company',
    nodeStatus: 'Node',
    links: {
      features: 'Features',
      pricing: 'Pricing & licenses',
      dashboard: 'Dashboard',
      launcher: 'Launcher builder',
      docs: 'Documentation',
      quickstart: 'Quick start',
      api: 'Developer API',
      status: 'Platform status',
      projects: 'Projects on FloV:MP',
      roadmap: 'Roadmap',
      contact: 'Contact',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
    },
  },

  home: {
    badge: 'SaaS platform & multiplayer engine',
    h1a: 'Own your',
    h1accent: 'GTA V project',
    h1b: 'infrastructure',
    sub: 'Launch and manage RP projects from one panel: network runtime, licensing, cloud server console, telemetry, billing and SDK. Fully independent from Take-Two, RAGE:MP and the alt:V backend.',
    ctaPrimary: 'Buy a Lifetime license',
    ctaSecondary: 'Read the docs',
    trustLine: 'One node = one VDS. FastDL CDN included. HMAC-SHA256 key verification.',

    statsTitle: 'Platform in numbers',
    stats: {
      projects: 'Active projects',
      servers: 'Game servers',
      players: 'Players online',
      uptime: 'Uptime over 90 days',
    },

    pillarsTitle: 'Three platform pillars',
    pillars: [
      {
        n: '01',
        t: 'Autonomous runtime',
        d: 'The server starts on your VDS and runs independently. C# .NET 8 for logic, V8 for the client UI. No master lists, no external dependencies.',
      },
      {
        n: '02',
        t: 'Cloud control',
        d: 'A txAdmin-style web console: live SSE log stream, restart, kick, RCON and a hot resource manager that never drops the server.',
      },
      {
        n: '03',
        t: 'Control & protection',
        d: 'FloV:ID and HWID policies (Strict / Lenient / Disabled), anti-VPN, cryptographic license verification and server-side control of every transaction.',
      },
    ],

    featuresTitle: 'What the platform includes',
    featuresSub: 'Everything to launch and grow an RP project — out of the box, no third-party plugins to assemble.',
    features: [
      { t: '3D voice chat', d: 'Native WebRTC + Opus. Spatial audio, faction radios, megaphones, sound zones.' },
      { t: 'World sync', d: 'Peds, traffic, quest NPCs and combat enemies — in sync for every player.' },
      { t: 'Cloud console', d: 'Real-time SSE logs, RCON, restart and kick straight from the browser.' },
      { t: 'Resource manager', d: 'Start / stop / restart scripts, maps and packs without restarting the server, with dependency control.' },
      { t: '60 Hz telemetry', d: 'Tick rate, server FPS, CoreCLR memory, a 24h online graph and a 99.98% SLA.' },
      { t: 'Launcher builder', d: 'Branded Setup.exe: name, color, logo, FloV:Graphics (DLSS / FSR).' },
      { t: 'Key verification', d: 'FLV-XXXX-XXXX-XXXX format, HMAC-SHA256 signature, auto IP binding, 7-day grace period.' },
      { t: 'Developer API', d: 'Public status and player endpoints, Discord / Telegram webhooks, donation intake.' },
    ],

    quickstartTitle: 'First server launch',
    quickstartSub: 'From the engine archive to accepting players — one evening with the guide.',
    quickstartPort: 'Network port',
    quickstartConsole: 'In-game console',
    quickstartConsoleVal: 'F8 key in the client + web console in the dashboard',
    quickstartCmds: 'Built-in admin commands',
    cmds: [
      ['/o <text>', 'global broadcast to every player'],
      ['/pos', 'player coordinates X, Y, Z for mapping'],
      ['/setdim <name> <world>', '0 — street, 999 — admin jail, 10000+ — houses'],
      ['/veh <model>', 'spawn any GTA V vehicle'],
      ['/stats', 'player, ping and hardware summary'],
    ],
    quickstartBans: 'Multi-level ban system',
    bans: [
      ['/ban', 'account ban'],
      ['/banip', 'IP ban'],
      ['/bansc', 'Rockstar Social Club license ban'],
      ['/hwidban', 'hardware ban (FloV:ID)'],
      ['/hardban', 'total: Account + IP + SC + HWID + MAC'],
      ['/unban', 'universal unban'],
    ],

    ownershipTitle: 'Full control over your server',
    ownershipSub:
      'FloV:MP imposes no lore and hides no locks. Any map — real Moscow, the 19th-century Wild West or custom islands.',
    ownership: [
      { t: '"Blank canvas" — Blank C# SDK', d: 'An empty C# .NET 8 project for unique mechanics with your own architecture.' },
      { t: '"RP Starter" — ready base', d: 'Economy, admin system, inventory and interior dimensions out of the box.' },
    ],

    projectsTitle: 'Projects already on FloV:MP',
    projectsSub: 'Each project groups several servers: production, development, test.',
    projectsCta: 'All projects',

    ctaTitle: 'Connect your RP server today',
    ctaSub: 'We will show how to migrate from RAGE:MP or FiveM and help with the first launch.',
  },

  features: {
    title: 'Platform features',
    sub: 'A detailed look at what FloV:MP is made of: the network engine, cloud control, security and developer tools.',
    groups: [
      {
        t: 'Network engine',
        items: [
          ['Autonomous runtime', 'altv-server v16.4.39 (unhooked). The whole network stack — EntityStreamer, SyncSend/Receive, NetworkWorker — comes up locally with no alt:V backend calls.'],
          ['C# .NET 8 gamemode', 'CoreCLR module, full engine API access, resource hot-reload, a type-safe SDK (NuGet).'],
          ['NUI client in JS/TS', 'HUD, menus, cameras and UIs in HTML/CSS/JS. Reuse your RAGE:MP and FiveM work.'],
          ['World sync', 'A living city with bots, quest and combat NPCs, synced traffic, weather and time.'],
        ],
      },
      {
        t: 'Cloud control',
        items: [
          ['txAdmin Cloud Console', 'A two-way agent on the game server. Live SSE console stream to the browser, RCON, restart, kick, broadcast.'],
          ['Dynamic Resource Manager', 'Start / stop / restart individual scripts, maps, car packs and NUI without restarting the server. Dependency graph.'],
          ['Watchdog & crashes', 'Hang supervisor > 15 s, CoreCLR stack dump, auto-restart (limit 5 / hour), crash log.'],
          ['Project environments', 'Production, Development, Test Sandbox — separate license bindings and telemetry.'],
        ],
      },
      {
        t: 'Security',
        items: [
          ['FloV:ID & HWID', 'PC hardware identifiers. Strict / Lenient / Disabled policies, account limit per machine.'],
          ['Anti-VPN', 'Detects and blocks VPN / proxy on connect, allow-lists.'],
          ['License verification', 'FLV-XXXX-XXXX-XXXX format, HMAC-SHA256 signed response, auto-binding of the first external IP.'],
          ['Grace period', 'The server caches the license locally and runs up to 7 days if the portal is unreachable.'],
        ],
      },
      {
        t: 'Developer tools',
        items: [
          ['Launcher Builder', 'Branded Setup.exe: name, HEX color, logo, FloV:Graphics (DLSS / FSR, GPU detection).'],
          ['Public Developer API', '/status, /players, /donate (X-Signature HMAC check) — for monitors and external sites.'],
          ['Webhooks', 'Discord Rich Embeds and the Telegram Bot API: crashes, load peaks, recovery, HWID policy hits.'],
          ['SDK & FastDL', 'Linux/Win cores, C# SDK, Asset Packer CLI, code snippets, gigabit HTTP/2 content delivery.'],
        ],
      },
    ],
  },

  pricing: {
    title: 'Pricing & licenses',
    sub: 'The starter license is free. Discounts for 6 or 12 months. Affiliate program — 20% for life.',
    periodMonth: '1 month',
    periodHalf: '6 months',
    periodYear: '1 year',
    popular: 'Popular choice',
    cta: 'Choose plan',
    ctaFree: 'Start for free',
    plans: [
      {
        id: 'starter',
        name: 'Starter',
        tagline: 'For developing and testing a new server',
        priceMonth: 'Free',
        note: '30 days',
        features: ['Up to 128 players', 'Autonomous engine binaries', 'C# Gamemode SDK', '1 IP binding', 'Cloud console (read-only)'],
      },
      {
        id: 'pro',
        name: 'Pro',
        tagline: 'For launching a full RP project',
        priceMonth: '$179',
        note: 'per project',
        features: ['Up to 512 players', '"RP Starter" ready base', '3D voice + NPC sync', 'txAdmin Cloud + Resource Manager', 'FloV:ID / HWID policies', 'Discord / Telegram webhooks'],
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        tagline: 'For large projects and franchises',
        priceMonth: '$590',
        note: 'per project',
        features: ['1500+ players', 'Branded launcher', 'Turnkey RAGE:MP / FiveM migration', 'Dedicated support · SLA 99.9%', 'Roadmap priority'],
      },
    ],
    faqTitle: 'Billing questions',
    faq: [
      ['How does the Lifetime license work?', 'One license is tied to a project forever. Inside a project you can have any number of servers (production / dev / test), a shared SDK and API keys.'],
      ['What about renewals?', 'Pro and Enterprise are per-project subscriptions. Auto-renewal can be toggled in the dashboard. −15% for 6 months, −30% for a year.'],
      ['How do I pay?', 'Card, SBP QR or USDT. License activation is instant once payment is confirmed.'],
      ['Affiliate program?', '20% of payments from referred projects — for life. Promo code and stats live in the dashboard Settings.'],
    ],
  },

  projects: {
    title: 'Projects on FloV:MP',
    sub: 'A showcase of RP projects deployed on top of the platform. Public status updates in real time.',
    thServers: 'servers',
    thOnline: 'online',
    thPeak: 'peak',
    visit: 'Visit',
  },

  roadmap: {
    title: 'Roadmap',
    sub: 'Upcoming milestones for the engine and the SaaS platform. Enterprise customer priorities come first.',
    statusDone: 'Done',
    statusActive: 'In progress',
    statusPlanned: 'Planned',
    items: [
      { q: 'Q3 2026', t: 'Autonomous runtime', s: 'done', d: 'Unhooking alt:V binaries, local network stack start, FastDL CDN, HMAC key verification.' },
      { q: 'Q3 2026', t: 'SaaS portal MVP', s: 'done', d: 'Licenses, environments, billing, telemetry, launcher builder, public API.' },
      { q: 'Q4 2026', t: 'txAdmin Cloud Console', s: 'active', d: 'Two-way agent, SSE log stream, RCON, resource manager, watchdog.' },
      { q: 'Q4 2026', t: 'FloV:ID / HWID', s: 'active', d: 'Hardware identifiers, Strict / Lenient / Disabled policies, anti-VPN.' },
      { q: 'Q1 2027', t: '2FA and RBAC', s: 'planned', d: 'TOTP, Owner / Project Lead / Developer roles, team action audit.' },
      { q: 'Q1 2027', t: 'Load test 3000+', s: 'planned', d: 'Stress test of the network stack and streaming at thousands of players.' },
      { q: 'Q2 2027', t: 'Auto-deploy & hosting', s: 'planned', d: 'One-click deploy from a branch, REDL Hosting integration, snapshots.' },
    ],
  },

  contact: {
    title: 'Contact',
    sub: 'Tell us about your project — we will suggest a plan and help with migration and the first launch.',
    tgTitle: 'Telegram',
    tgDesc: 'Fast replies on weekdays, migration talk and tech questions.',
    dsTitle: 'Discord',
    dsDesc: 'Developer community, update announcements and platform status.',
    formTitle: 'Send a request',
    formName: 'Name or nickname',
    formContact: 'Telegram / Email',
    formProject: 'About the project',
    formSubmit: 'Send request',
    formNote: 'This is a demo form — message us on Telegram for a real reply.',
  },

  dash: {
    hello: 'Welcome',
    roleAdmin: 'Administrator',
    roleClient: 'SaaS client',
    headerSub: 'Licenses, VDS telemetry, billing and the branded FloV:MP launcher',
    newLicense: 'New license',
    loading: 'Loading the FloV:MP control panel…',
    refresh: 'Refresh',
    cancel: 'Cancel',
    tabs: {
      projects: 'Projects & servers',
      console: 'txAdmin console',
      troubleshoot: 'AI diagnostics',
      overview: 'Keys & status',
      telemetry: 'VDS telemetry',
      sdk: 'Downloads & SDK',
      builder: 'Launcher builder',
      billing: 'Billing & invoices',
      affiliate: 'Affiliate (20%)',
      analytics: 'Analytics',
      watchdog: 'Watchdog & crashes',
      logs: 'Logs',
      api: 'API & webhooks',
      settings: 'Settings',
    },
    buildStages: ['Generating configuration…', 'Packing Electron + Native Bridge…', 'Signing EXE…', 'Done'],
    toast: {
      errLoad: 'Failed to load dashboard data',
      errLoadServers: 'Failed to load the project servers',
      errSave: 'Save error',
      settingsSaved: 'Project and webhook settings saved',
      errSend: 'Send error',
      alertsSent: 'Test alerts sent',
      errResource: 'Resource control error',
      sseOff: 'Live SSE console stream disabled',
      sseOn: 'Live SSE console stream enabled',
      sseErr: 'Could not connect to the SSE stream',
      errCreateProj: 'Project creation error',
      projCreated: 'New project created',
      errCmd: 'Command dispatch error',
      pasteLogs: 'Paste a server log fragment to analyze',
      errAnalyze: 'Log analysis error',
      aiDone: 'AI diagnostics complete',
      errBindIp: 'IP binding error',
      ipSaved: 'IP address saved',
      errCreateLic: 'License creation error',
      licActivated: 'License activated',
      errPay: 'Payment error',
      payConfirmed: 'Payment confirmed',
      errInvoice: 'Invoice creation error',
      hbRecorded: 'Heartbeat packet recorded',
      errTelemetry: 'Telemetry write error',
      needActiveLic: 'An active license is required to build',
      errBuild: 'Launcher build error',
      launcherBuilt: 'Custom launcher built',
      consoleCleared: 'Console cleared',
      err: 'Error',
      cmdToAgent: 'Command sent to the agent',
      cmdQueued: 'Command queued',
      invoiceIssued: 'Invoice issued',
      twoFaOn: 'Two-factor authentication enabled',
      twoFaOff: 'Two-factor authentication disabled',
      twoFaErr: 'Wrong confirmation code',
      accSaved: 'Account details saved',
    },
    proj: {
      title: 'FloV:MP ecosystem projects',
      hierarchy: 'Hierarchy: Account → Project (license) → Game servers (Prod / Dev / Test)',
      create: 'Create project',
      slots: 'slots',
      activeProject: 'Active project',
      plan: 'Plan',
      limit: 'Limit',
      copyLicenseKey: 'Copy License Key',
      copyAgentKey: 'Copy Agent API Key',
      settingsWebhook: 'Settings & webhook',
      envTitle: 'Server environments',
      envSub: 'The txAdmin Cloud agent on every node listens for commands and sends telemetry',
      serversCount: 'Servers',
      noServers: 'This project has no running servers yet.',
      agentActive: 'Agent Active',
      slotsShort: 'Slots',
      protocol: 'Protocol',
      agent: 'Agent',
      restart: 'Restart',
      stop: 'Stop',
      announce: 'Announce to players',
      resTitle: 'Server resource manager',
      resSub: 'Start, stop and restart scripts, maps and vehicles on the fly without restarting the node',
      resReload: 'Reload resources',
      thResource: 'Resource',
      thType: 'Type',
      thVersion: 'Version',
      thStatus: 'Status',
      thControl: 'Control',
      running: 'Running',
      stopped: 'Stopped',
      resRestart: 'Restart resource',
      resStop: 'Stop resource',
      resStart: 'Start resource',
    },
    console: {
      title: 'txAdmin Cloud Web Console',
      sub: 'A direct two-way control channel to the FloV:MP server via RemoteServerAgent',
      agentConnected: 'Agent Connected (UDP 7788)',
      sseTitle: 'Real time with no lag over Server-Sent Events',
      sseOn: 'SSE active',
      sseOff: 'Enable SSE',
      clear: 'Clear',
      chipReboot: 'Reboot with announcement',
      chipRebootCmd: 'broadcast Attention: reboot in 5 minutes!',
      chipStatus: 'Request player status',
      chipGc: 'Force GC',
      chipBattleye: 'Check BattlEye',
      placeholder: 'broadcast [text], restart, stop or a server command…',
      send: 'Send',
    },
    ai: {
      title: 'FloV:AI — failure diagnostics and auto-fix',
      sub: 'Analysis of server startup logs, CoreCLR (.NET) crashes, UDP 7788 ports, BattlEye and resource.toml',
      presetsLabel: 'Common failure presets for a quick check:',
      pCoreclr: 'CoreCLR (.NET) crash',
      pUdp: 'UDP 7788 blocked',
      pBin: 'Missing .bin files',
      pToml: 'resource.toml error',
      inputLabel: 'altv-server error log fragment or a C# exception',
      inputPlaceholder: 'Paste the error text here (e.g. FATAL [CoreCLR] System.Exception: …)',
      analyzing: 'Neural log analysis…',
      diagnose: 'Diagnose the error',
      category: 'Category',
      cause: 'Incident cause:',
      solution: 'Step-by-step solution:',
      docs: 'Documentation',
    },
    overview: {
      quickStart: 'Project quick start',
      stepAccount: 'Account created',
      stepLicense: 'License active',
      stepLicenseNo: 'Not created',
      stepPlan: 'Plan',
      stepIp: 'Server IP bound',
      stepIpNo: 'Binding required',
      stepNode: 'Network node online',
      yourLicenses: 'Your licenses',
      licSub: 'Every key binds to the game server IPv4',
      total: 'Total',
      noLicenses: 'You have no active licenses yet',
      createFirst: 'Create your first license',
      planLabel: 'Plan',
      active: 'Active',
      suspended: 'Suspended',
      hideKey: 'Hide key',
      showKey: 'Show key',
      copyKey: 'Copy key',
      ipAny: 'any (0.0.0.0)',
      slotsShort: 'Slots',
      expires: 'Expires',
      configureIp: 'Configure IP',
      server: 'Server',
      tomlTitle: 'Add the key to',
      tomlStep1: 'Download the engine archive with the "Server" button on the license card.',
      tomlStep2: 'In',
      tomlStep2b: 'add the block:',
      tomlStep3a: 'Run',
      tomlStep3b: '— the node passes online verification and starts accepting players.',
    },
    tele: {
      title: 'Game node monitoring',
      testHeartbeat: 'Test heartbeat',
      tickFoot: 'Sync 16.6 ms',
      fpsFoot: 'Physics with no drops',
      ramFoot: 'RAM optimized',
      playersLabel: 'Players online',
      playersFoot: 'Slots active',
      curveTitle: 'Daily player online dynamics (24h activity)',
      curveSub: 'Hourly project server activity with peak online and SLA uptime',
      peak: 'Peak',
      peakVal: '184 players',
      night: 'Night',
      morning: 'Morning',
      day: 'Day',
      prime: 'Prime time',
      historyTitle: 'Telemetry packet history (last 30)',
      noPackets: 'No packets recorded. Click "Test heartbeat" to send a packet from the bench.',
      thTime: 'Time',
      thNodeIp: 'Node IP',
      thOnline: 'Online',
      thRam: 'RAM',
    },
    sdk: {
      title: 'FloV:MP distributions and SDK',
      sub: 'Autonomous multiplayer runtime, CoreCLR modules, the C# SDK library and FastDL utilities',
      items: [
        ['FloV:MP Server Core (Linux)', 'Autonomous runtime for VDS Ubuntu 22.04 / Debian 12. Includes coreclr-module, BattlEye and the UDP streamer.', 'Download tar.gz'],
        ['FloV:MP Server Core (Windows)', 'Local development server for Windows 10/11/Server 2022. Full isolation from external backends.', 'Download zip'],
        ['FloVMP.Core C# .NET 8 SDK', 'C# API package: EntityStreamer, RemoteServerAgent, FactionEngine, LicensingService for building gamemodes.', 'Download SDK'],
        ['FloV:MP Asset Packer (CLI)', 'A console tool to encrypt client resources and auto-generate FastDL manifests before release.', 'Download Packer'],
        ['Electron Launcher Template', 'Source of a branded launcher on Chromium UI + C# Native Bridge with hardware acceleration.', 'Download template'],
        ['Gamemode samples (Templates)', 'Ready RP project templates: RP base, drift server, DM arena with full C# typing.', 'Download samples'],
      ] as [string, string, string][],
    },
    builder: {
      title: 'Custom launcher builder',
      sub: 'Compile the installer for the project brand and IP',
      projectName: 'Project name',
      hexColor: 'Brand HEX color',
      serverIp: 'Server IP',
      udpPort: 'UDP port',
      compiling: 'Compiling…',
      compile: 'Compile the project launcher',
      statusTitle: 'Builder status',
      built: 'Launcher built',
      bProject: 'Project',
      bColor: 'Color',
      bEndpoint: 'Endpoint',
      bLicense: 'License',
      download: 'Download',
      waiting: 'Waiting for a build to start',
      waitingSub: 'Set the parameters on the left and click "Compile". The builder packs Electron + C# Native Bridge and the FastDL manifest.',
      feat: [
        'Chromium UI hardware acceleration (blur / shadows)',
        'Direct C# .NET 8 connector (FloVMP.Connect)',
        'Embedded FastDL cache with the VDS CDN',
      ],
    },
    billing: {
      title: 'Invoices and subscription management',
      sub: 'Invoices are generated automatically, license renewal is instant',
      issue: 'Issue a renewal invoice',
      historyTitle: 'Issued invoice history',
      noInvoices: 'No invoices yet.',
      issueShort: 'Issue an invoice',
      thNo: 'No.',
      thPlan: 'Plan',
      thAmount: 'Amount',
      thMethod: 'Method',
      thCreated: 'Created',
      thStatus: 'Status',
      thAction: 'Action',
      paid: 'Paid',
      pending: 'Awaiting payment',
      closed: 'Closed',
      pay: 'Pay',
    },
    aff: {
      program: 'Affiliate program',
      earn: 'Earn 20% of server payments',
      descA: 'Recommend FloV:MP to GTA V RP server owners. You get',
      descB: '20% for life',
      descC: 'on every license renewal of a referred project. The referred project gets a discount of',
      descD: '10%',
      copied: 'Copied',
      copy: 'Copy',
      invited: 'Projects referred',
      activeRefs: 'Active referrals',
      earned: 'Rewards accrued',
      available: 'Available to withdraw',
      percent: 'Payout share',
      lifetime: 'For life on every payment',
    },
    modal: {
      bindIpTitle: 'Bind the server IP address',
      bindIpDesc: 'The public IPv4 address of the VDS where the game server runs',
      serverName: 'Server name',
      ipv4: 'IPv4 address',
      saveBinding: 'Save binding',
      newLicTitle: 'New license',
      newLicDesc: 'Choose a plan for the scale of your game project',
      indie: 'Indie',
      free: 'Free',
      yourServerName: 'Your server name',
      ipLater: 'Server IP (can be set later)',
      activateLic: 'Activate license',
      newProjTitle: 'Create a new project',
      newProjDesc: 'A project groups one license and several environments: Production, Development, Test',
      slugLabel: 'Slug identifier (project URL)',
      settingsTitle: 'Project settings & webhooks',
      settingsDesc: 'FloV:ID security policy, HWID bypass tolerance and Discord / Telegram alerts',
      hwidPolicy: 'FloV:ID and HWID security policy',
      hwidStrict: 'Strict',
      hwidStrictDesc: 'Block banned HWIDs',
      hwidLenient: 'Lenient',
      hwidLenientDesc: 'Login allowed with audit',
      hwidDisabled: 'Disabled',
      hwidDisabledDesc: 'Let everyone in with no limits',
      maxAccs: 'Max accounts per HWID',
      allowVpn: 'Allow players to connect via VPN / Proxy',
      alertsTitle: 'Discord and Telegram alerts',
      alertsSub: 'Automatic notifications on server downtime, crashes and load spikes',
      enabled: 'Enabled',
      test: 'Test',
      saveProjectParams: 'Save project parameters',
      invoiceTitle: 'Issue an invoice',
      invoiceDesc: 'Choose a plan, period and payment method',
      planLabel: 'Plan',
      periodLabel: 'Billing period',
      methodLabel: 'Payment method',
      pMonth: '1 month',
      pHalf: '6 mo · −15%',
      pYear: '1 year · −30%',
      mCard: 'Card',
      mSbp: 'SBP QR',
      issueInvoice: 'Issue invoice',
    },
    wd: {
      title: 'Watchdog & crashes',
      sub: 'Main-thread hang supervisor and automatic CoreCLR restart',
      threshold: 'Hang threshold',
      thresholdVal: '15.0 s',
      restarts: 'Auto-restarts this hour',
      restartsVal: '2 / 5',
      uptime: 'Supervisor uptime',
      uptimeVal: '30 days',
      crashLog: 'Crash log',
      thTime: 'Time',
      thServer: 'Server',
      thReason: 'Reason',
      thRestarted: 'Restarted',
      ok: 'Recovered',
      failed: 'Did not recover',
      dumpTitle: 'CoreCLR stack dump — last crash',
      rows: [
        ['2026-09-06 09:12:44', 'florida-prod-02', 'CoreCLR SIGSEGV in econ_core.PayrollTick', true],
        ['2026-09-05 22:41:03', 'florida-dev', 'Watchdog: main thread hang 18.3 s', true],
        ['2026-09-04 03:07:19', 'florida-prod-01', 'OOM — heap 7.8 GB / 8 GB', true],
      ] as [string, string, string, boolean][],
    },
    logs: {
      title: 'System logs',
      sub: 'Project event history — search and filter by level',
      search: 'Search by message or source',
      notFound: 'Nothing found',
      rows: [
        ['2026-09-06 12:41:07', 'INFO', 'network', 'player connected id=41 "Mikhail_D" ip=***.***.14.2'],
        ['2026-09-06 12:41:05', 'INFO', 'license', 'license FLV-•••• verified · slots 1500 · sig ok'],
        ['2026-09-06 12:41:04', 'OK', 'fastdl', 'FastDL manifest verified (2 184 files, 6.1 GB)'],
        ['2026-09-06 12:40:58', 'WARN', 'gamemode', 'tick spike 22ms on resource econ_core'],
        ['2026-09-06 12:40:32', 'INFO', 'api', 'API key rotated · project florida-v · by Anna K.'],
        ['2026-09-06 12:39:11', 'ERROR', 'voice', 'webrtc renegotiation failed for peer 88 — retry scheduled'],
        ['2026-09-06 12:38:00', 'INFO', 'agent', 'deploy florida-prod-01 → v16.4.39 completed in 41s'],
        ['2026-09-06 12:20:05', 'OK', 'db', 'MariaDB pool healthy · 12/50 connections'],
        ['2026-09-06 12:04:49', 'WARN', 'monitoring', 'CPU 82% on florida-prod-01 for 3m — alert sent'],
        ['2026-09-06 09:12:44', 'CRASH', 'watchdog', 'CoreCLR SIGSEGV — core dumped, autorestart ok'],
      ] as [string, string, string, string][],
    },
    an: {
      title: 'Project and server analytics',
      sub: 'Online, load and network over the last 24 hours. Game node telemetry data.',
      peak: 'Peak online',
      peakVal: '2,310',
      avg: 'Average online',
      avgVal: '1,460',
      sla: 'Uptime · SLA',
      slaVal: '99.98%',
      cOnline: 'Players online',
      cCpu: 'CPU load',
      cRam: 'RAM usage',
      cNet: 'Network traffic',
      gCpu: 'CPU now',
      gRam: 'RAM now',
      gNet: 'Network',
      gFoot: 'average across project servers',
      h24: '24h',
    },
    api: {
      title: 'API & webhooks',
      sub: 'Access keys, public endpoints and Discord / Telegram alerts',
      baseUrl: 'Project base URL',
      agentKey: 'Agent API Key',
      keyHint: 'The RemoteServerAgent key on the game server. Do not publish it.',
      rotate: 'Rotate',
      rotating: 'Rotating…',
      rotated: 'Agent API Key rotated',
      show: 'show',
      hide: 'hide',
      copy: 'Copy',
      copied: 'Copied',
      publicTitle: 'Public endpoints (Developer API)',
      publicSub: 'For monitors, project sites and the donation shop. HMAC X-Signature header for /donate.',
      epStatus: 'online, players, version, ping, uptime',
      epPlayers: 'server player list',
      epDonate: 'donation intake from external sites (X-Signature check)',
      webhooksTitle: 'Discord / Telegram webhooks',
      webhooksSub: 'Configured in the "Settings & webhook" modal on the "Projects & servers" tab.',
      whDiscord: 'Discord Webhook',
      whTelegram: 'Telegram Bot',
      whOn: 'connected',
      whOff: 'not set',
      openSettings: 'Open project settings',
      noProject: 'Pick a project on the "Projects & servers" tab first.',
    },
    sec: {
      accountTitle: 'Account',
      name: 'Name',
      email: 'Email',
      telegram: 'Telegram',
      save: 'Save',
      twoFaTitle: 'Two-factor authentication (TOTP)',
      twoFaOnDesc: 'Enabled · a code from your app is required at sign-in',
      twoFaOffDesc: 'Not set up — we recommend enabling it to protect your account',
      enable: 'Enable 2FA',
      disable: 'Disable 2FA',
      setupHint: 'Add the key to an authenticator app (Google Authenticator, Authy, 1Password), then enter a code.',
      secretLabel: 'Key (manual entry)',
      uriLabel: 'otpauth link',
      codeLabel: 'Code from the app',
      confirm: 'Confirm and enable',
      cancel: 'Cancel',
      refTitle: 'Affiliate program · 20% RevShare',
      refCode: 'Your promo code',
      copied: 'Copied',
      copy: 'Copy',
      refInvited: 'Referred',
      refEarned: 'Accrued',
      refShare: 'Share',
      sessionsTitle: 'Active sessions',
      sessionCurrent: 'this',
      sessionRevoke: 'Revoke',
      sessions: [
        ['Chrome · Windows 11', '188.127.•.14', 'Moscow, RU', 'now', true],
        ['FloV:MP Launcher', '188.127.•.14', 'Moscow, RU', '2 h ago', false],
        ['Safari · iPhone', '31.173.•.88', 'Kazan, RU', 'yesterday', false],
      ] as [string, string, string, string, boolean][],
    },
  },

  adm: {
    accessDenied: 'Access denied: an administrator account is required',
    loadFailed: 'Failed to load platform data',
    err: 'Error',
    loading: 'Loading the admin panel…',
    refresh: 'Refresh',
    mRevenue: 'Total revenue',
    mServers: 'Total servers',
    mLicenses: 'Active licenses',
    mClients: 'Total clients',
    headerTitle: 'Platform and server registry management',
    headerSub: 'Control of licenses, clients, payments and node status',
    allLicenses: 'All issued licenses',
    thServerProject: 'Server / project',
    thKey: 'Key',
    thPlan: 'Plan',
    thStatus: 'Status',
    thExpires: 'Expires',
    thActions: 'Actions',
    active: 'Active',
    suspended: 'Suspended',
    freeze: 'Freeze',
    unfreeze: 'Unfreeze',
    clients: 'Clients',
    thLogin: 'Username',
    thRole: 'Role',
    thCreated: 'Created',
    txRegistry: 'Transaction registry',
    thClient: 'Client',
    thAmount: 'Amount',
    thDate: 'Date',
    paid: 'Paid',
    pending: 'Pending',
    noTx: 'No transactions yet.',
    logNote: 'All operations are logged',
  },

  auth: {
    loginTitle: 'Sign in',
    loginSub: 'Manage FloV:MP licenses, servers and billing',
    registerTitle: 'Sign up for FloV:MP',
    registerSub: 'A free Starter license for 128 slots — right after you create the account',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least 6 characters',
    username: 'Username',
    telegram: 'Telegram',
    signIn: 'Sign in',
    signInBusy: 'Signing in…',
    createAccount: 'Create account',
    createBusy: 'Creating account…',
    noAccount: 'No account?',
    haveAccount: 'Already have an account?',
    toRegister: 'Sign up',
    toLogin: 'Sign in',
    freeLicenseNote: 'A Starter license (128 slots, 30 days) is created automatically on sign-up.',
    errGeneric: 'Something went wrong. Please try again.',
  },

  docs: {
    title: 'Documentation & API',
    sub: 'License verification, telemetry, the cloud agent and FastDL setup. The interactive examples send real requests to the portal API.',
    navQuickstart: 'Quick start',
    navVerify: 'License verification',
    navAgent: 'Cloud agent',
    navTelemetry: 'Telemetry',
    navSdk: 'SDK & snippets',
    navFastdl: 'FastDL (Nginx)',

    quickstartTitle: 'First server launch',
    quickstartLead: 'From unpacking the engine archive to accepting players — step by step.',
    steps: [
      ['1. Distribution', 'Download the Linux server core in the dashboard and unpack it on your VDS. Copy the engine .bin files into the working folder.'],
      ['2. server.toml', 'Set the license key FLV-XXXX-XXXX-XXXX, the public server IPv4 and the FastDL CDN URL.'],
      ['3. Port', 'Open UDP 7788 (next-gen alt:V protocol, autonomous start).'],
      ['4. Launch', 'Run ./start.sh — the node passes HMAC online verification and starts accepting players.'],
      ['5. Console', 'The F8 key opens the in-game console; the web console lives in the dashboard (SSE stream).'],
    ],
    reqTitle: 'Request body',
    resTitle: 'API response',
    runVerify: 'Run a test verification',
    running: 'Sending request…',
    verifyHint: '// Click the button — a JSON with an HMAC-SHA256 signature appears here',
    agentHint: '// Connect — a live console stream opens here (demo)',
    verifyDesc: 'The endpoint the server calls on start and every 15 minutes. It checks key status, IPv4 binding and signs the response with HMAC-SHA256.',
    agentDesc: 'A two-way agent on the game server polls the command queue and streams console output to the browser via Server-Sent Events. Commands: restart, stop, broadcast, kick_all, resource_start / stop / restart, execute.',
    telemetryDesc: 'The server sends a packet every minute: online, tick rate, FPS, CoreCLR memory. The last 30 packets build the charts in the Analytics section.',
    sdkDesc: 'Ready snippets for the AltV.Net server gamemode, Node.js and the FastDL config.',
    fastdlDesc: 'Client file delivery at gigabit speed over HTTP/2. The game UDP channel stays unloaded.',
    fastdlFacts: [
      ['Cache-Control', 'immutable, 30 days'],
      ['Protocol', 'HTTP/2 + sendfile'],
      ['UDP load', '0% — channel unloaded'],
    ],
  },

  notFound: {
    title: 'Page not found',
    sub: 'This page does not exist or has been moved.',
  },
};

export const DICT: Record<Lang, typeof ru> = { ru, en };
