"""Генератор src/natives.h: берёт хэши и сигнатуры нужных нативных функций
GTA V из натив-заголовка ScriptHookV SDK (сам SDK в репозиторий не кладётся,
его распространение запрещено автором) и пишет собственные обёртки.

  python tools/gen_natives.py <путь к ScriptHookV_SDK/inc/natives.h>
"""
import pathlib
import re
import sys

WANTED = """
PLAYER_ID PLAYER_PED_ID GET_PLAYER_NAME SET_PLAYER_MODEL SET_PLAYER_CONTROL SET_PLAYER_INVINCIBLE
SET_MAX_WANTED_LEVEL CLEAR_PLAYER_WANTED_LEVEL SET_EVERYONE_IGNORE_PLAYER SET_POLICE_IGNORE_PLAYER
SET_DISPATCH_COPS_FOR_PLAYER SET_RUN_SPRINT_MULTIPLIER_FOR_PLAYER IS_PLAYER_FREE_AIMING
GET_ENTITY_PLAYER_IS_FREE_AIMING_AT IS_PLAYER_SWITCH_IN_PROGRESS SET_PLAYER_WANTED_LEVEL SET_PLAYER_WANTED_LEVEL_NOW
GET_ENTITY_COORDS GET_ENTITY_HEADING SET_ENTITY_HEADING SET_ENTITY_COORDS SET_ENTITY_COORDS_NO_OFFSET
GET_ENTITY_VELOCITY SET_ENTITY_VELOCITY GET_ENTITY_ROTATION SET_ENTITY_ROTATION GET_ENTITY_HEALTH
SET_ENTITY_HEALTH GET_ENTITY_MAX_HEALTH SET_ENTITY_MAX_HEALTH IS_ENTITY_DEAD DOES_ENTITY_EXIST DELETE_ENTITY
SET_ENTITY_AS_MISSION_ENTITY SET_ENTITY_INVINCIBLE FREEZE_ENTITY_POSITION SET_ENTITY_COLLISION
SET_ENTITY_VISIBLE SET_ENTITY_ALPHA RESET_ENTITY_ALPHA HAS_ENTITY_BEEN_DAMAGED_BY_ENTITY
CLEAR_ENTITY_LAST_DAMAGE_ENTITY GET_ENTITY_SPEED GET_ENTITY_MODEL SET_ENTITY_PROOFS
SET_ENTITY_CAN_BE_DAMAGED SET_ENTITY_DYNAMIC SET_ENTITY_LOAD_COLLISION_FLAG SET_ENTITY_NO_COLLISION_ENTITY
GET_ENTITY_FORWARD_VECTOR GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS SET_ENTITY_AS_NO_LONGER_NEEDED
GET_ENTITY_HEIGHT_ABOVE_GROUND IS_ENTITY_IN_WATER SET_ENTITY_HAS_GRAVITY
IS_PED_IN_ANY_VEHICLE GET_VEHICLE_PED_IS_IN IS_PED_SHOOTING IS_PED_DUCKING IS_PED_JUMPING
IS_PED_RAGDOLL GET_PED_CAUSE_OF_DEATH _GET_PED_KILLER CREATE_PED SET_PED_INTO_VEHICLE
TASK_WARP_PED_INTO_VEHICLE SET_BLOCKING_OF_NON_TEMPORARY_EVENTS SET_PED_CAN_RAGDOLL SET_PED_CONFIG_FLAG
TASK_GO_STRAIGHT_TO_COORD TASK_STAND_STILL CLEAR_PED_TASKS CLEAR_PED_TASKS_IMMEDIATELY
TASK_AIM_GUN_AT_COORD TASK_SHOOT_AT_COORD SET_PED_DEFAULT_COMPONENT_VARIATION GIVE_WEAPON_TO_PED
SET_CURRENT_PED_WEAPON GET_SELECTED_PED_WEAPON REMOVE_ALL_PED_WEAPONS SET_PED_ARMOUR GET_PED_ARMOUR
SET_PED_CAN_BE_TARGETTED SET_PED_SUFFERS_CRITICAL_HITS SET_PED_DIES_WHEN_INJURED SET_PED_KEEP_TASK
SET_PED_CAN_SWITCH_WEAPON SET_PED_RELATIONSHIP_GROUP_HASH ADD_RELATIONSHIP_GROUP
SET_RELATIONSHIP_BETWEEN_GROUPS SET_PED_AMMO GET_PED_IN_VEHICLE_SEAT IS_PED_DEAD_OR_DYING
TASK_ENTER_VEHICLE TASK_LEAVE_VEHICLE GET_VEHICLE_PED_IS_TRYING_TO_ENTER GET_SEAT_PED_IS_TRYING_TO_ENTER
IS_PED_GETTING_INTO_A_VEHICLE SET_PED_CAN_BE_DRAGGED_OUT SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE
IS_PED_RELOADING SET_PED_INFINITE_AMMO_CLIP SET_PED_DESIRED_HEADING
SET_PED_FLEE_ATTRIBUTES SET_PED_COMBAT_ATTRIBUTES TASK_SET_BLOCKING_OF_NON_TEMPORARY_EVENTS
SET_PED_MOVE_RATE_OVERRIDE SET_PED_GRAVITY GET_PED_BONE_COORDS SET_PED_HEAD_BLEND_DATA TASK_JUMP SET_PED_ACCURACY
REQUEST_MODEL HAS_MODEL_LOADED SET_MODEL_AS_NO_LONGER_NEEDED IS_MODEL_IN_CDIMAGE IS_MODEL_A_VEHICLE IS_MODEL_VALID
REQUEST_COLLISION_AT_COORD
SET_PED_DENSITY_MULTIPLIER_THIS_FRAME SET_VEHICLE_DENSITY_MULTIPLIER_THIS_FRAME
SET_RANDOM_VEHICLE_DENSITY_MULTIPLIER_THIS_FRAME SET_PARKED_VEHICLE_DENSITY_MULTIPLIER_THIS_FRAME
SET_SCENARIO_PED_DENSITY_MULTIPLIER_THIS_FRAME SET_CREATE_RANDOM_COPS SET_RANDOM_TRAINS SET_RANDOM_BOATS
SET_GARBAGE_TRUCKS SET_NUMBER_OF_PARKED_VEHICLES SET_PED_POPULATION_BUDGET SET_VEHICLE_POPULATION_BUDGET
CLEAR_AREA_OF_PEDS CLEAR_AREA_OF_VEHICLES CLEAR_AREA_OF_COPS
SET_WEATHER_TYPE_NOW_PERSIST SET_OVERRIDE_WEATHER CLEAR_OVERRIDE_WEATHER CLEAR_WEATHER_TYPE_PERSIST
SET_CLOCK_TIME PAUSE_CLOCK NETWORK_OVERRIDE_CLOCK_TIME GET_CLOCK_HOURS GET_CLOCK_MINUTES
NETWORK_RESURRECT_LOCAL_PLAYER TERMINATE_ALL_SCRIPTS_WITH_THIS_NAME SET_FADE_OUT_AFTER_DEATH
SET_FADE_OUT_AFTER_ARREST SET_FADE_IN_AFTER_DEATH_ARREST IGNORE_NEXT_RESTART _DISABLE_AUTOMATIC_RESPAWN
_RESET_LOCALPLAYER_STATE DO_SCREEN_FADE_IN DO_SCREEN_FADE_OUT IS_SCREEN_FADED_OUT IS_SCREEN_FADED_IN
SHUTDOWN_LOADING_SCREEN GET_IS_LOADING_SCREEN_ACTIVE _STOP_ALL_SCREEN_EFFECTS
DISABLE_CONTROL_ACTION DISABLE_ALL_CONTROL_ACTIONS ENABLE_ALL_CONTROL_ACTIONS IS_CONTROL_JUST_PRESSED
IS_DISABLED_CONTROL_PRESSED IS_CONTROL_PRESSED GET_DISABLED_CONTROL_NORMAL GET_CONTROL_NORMAL
GET_FIRST_BLIP_INFO_ID GET_BLIP_INFO_ID_COORD IS_WAYPOINT_ACTIVE DOES_BLIP_EXIST GET_GROUND_Z_FOR_3D_COORD
_WORLD3D_TO_SCREEN2D ADD_BLIP_FOR_ENTITY REMOVE_BLIP SET_BLIP_COLOUR SET_BLIP_SPRITE SET_BLIP_AS_SHORT_RANGE
SET_BLIP_SCALE
SET_VEHICLE_FIXED SET_VEHICLE_ENGINE_ON _IS_VEHICLE_ENGINE_ON SET_VEHICLE_NUMBER_PLATE_TEXT
IS_VEHICLE_SEAT_FREE GET_VEHICLE_MAX_NUMBER_OF_PASSENGERS SET_VEHICLE_DOORS_LOCKED
SET_VEHICLE_ON_GROUND_PROPERLY SET_VEHICLE_FORWARD_SPEED CREATE_VEHICLE SET_VEHICLE_SIREN IS_VEHICLE_SIREN_ON
SET_VEHICLE_DIRT_LEVEL SET_VEHICLE_ENGINE_HEALTH SET_VEHICLE_BODY_HEALTH
SET_VEHICLE_HAS_BEEN_OWNED_BY_PLAYER SET_VEHICLE_NEEDS_TO_BE_HOTWIRED SET_VEHICLE_IS_STOLEN
SET_VEHICLE_STEER_BIAS
DISPLAY_RADAR DISPLAY_HUD HIDE_HUD_AND_RADAR_THIS_FRAME HIDE_HUD_COMPONENT_THIS_FRAME
GET_GAMEPLAY_CAM_ROT GET_GAMEPLAY_CAM_COORD
GET_HASH_KEY GET_GAME_TIMER GET_FRAME_TIME DESTROY_MOBILE_PHONE
SET_AUDIO_FLAG SET_CAN_ATTACK_FRIENDLY
IS_PAUSE_MENU_ACTIVE SET_GAME_PAUSED ACTIVATE_FRONTEND_MENU SET_PAUSE_MENU_ACTIVE _SET_RADAR_BIGMAP_ENABLED IS_PAUSE_MENU_RESTARTING SET_BLIP_FLASHES SET_BLIP_AS_FRIENDLY SET_BLIP_PRIORITY
_SHOW_CURSOR_THIS_FRAME DISPLAY_AREA_NAME SPECIAL_ABILITY_DEACTIVATE_FAST SET_PLAYER_HEALTH_RECHARGE_MULTIPLIER
IS_DISABLED_CONTROL_JUST_PRESSED IS_DISABLED_CONTROL_JUST_RELEASED DISABLE_CONTROL_ACTION IS_ENTITY_ON_SCREEN HAS_ENTITY_CLEAR_LOS_TO_ENTITY IS_ENTITY_IN_AIR
TERMINATE_THREAD IS_THREAD_ACTIVE _GET_THREAD_NAME _0xDADFADA5A20143A8 _0x30B4FA1C82DD4B9F GET_ID_OF_THIS_THREAD
REMOVE_CUTSCENE STOP_CUTSCENE_IMMEDIATELY IS_CUTSCENE_ACTIVE IS_CUTSCENE_PLAYING RENDER_SCRIPT_CAMS DESTROY_ALL_CAMS
SET_WIDESCREEN_BORDERS CLEAR_TIMECYCLE_MODIFIER SET_MISSION_FLAG STOP_SCRIPTED_CONVERSATION CLEAR_PRINTS
CLEAR_ALL_HELP_MESSAGES SET_CINEMATIC_MODE_ACTIVE IS_PLAYER_CONTROL_ON STOP_AUDIO_SCENES
HAS_COLLISION_LOADED_AROUND_ENTITY REQUEST_SCALEFORM_MOVIE HAS_SCALEFORM_MOVIE_LOADED _PUSH_SCALEFORM_MOVIE_FUNCTION
_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT _POP_SCALEFORM_MOVIE_FUNCTION_VOID ATTACH_ENTITY_TO_ENTITY DETACH_ENTITY
GET_VEHICLE_NUMBER_PLATE_TEXT GET_VEHICLE_ENGINE_HEALTH GET_VEHICLE_BODY_HEALTH
REQUEST_IPL REMOVE_IPL IS_IPL_ACTIVE GET_INTERIOR_AT_COORDS IS_VALID_INTERIOR REFRESH_INTERIOR
_ENABLE_INTERIOR_PROP _DISABLE_INTERIOR_PROP _IS_INTERIOR_PROP_ENABLED _LOAD_INTERIOR _LOAD_MP_DLC_MAPS PAUSE_CLOCK
CREATE_OBJECT_NO_OFFSET ADD_BLIP_FOR_COORD BEGIN_TEXT_COMMAND_SET_BLIP_NAME END_TEXT_COMMAND_SET_BLIP_NAME
_SET_VEHICLE_ENGINE_POWER_MULTIPLIER _SET_VEHICLE_ENGINE_TORQUE_MULTIPLIER SET_PED_TO_RAGDOLL SET_PED_DUCKING SET_VEHICLE_PETROL_TANK_HEALTH IS_WEAPON_VALID
_ADD_TEXT_COMPONENT_STRING DRAW_MARKER TASK_START_SCENARIO_IN_PLACE
""".split()
WANTED = list(dict.fromkeys(WANTED))  # без повторов: дубль — повторное определение функции

# Нынешние имена вместо имён SDK 2016 года.
RENAME = {
    "_GET_PED_KILLER": "GET_PED_SOURCE_OF_DEATH",
    "_DISABLE_AUTOMATIC_RESPAWN": "PAUSE_DEATH_ARREST_RESTART",
    "_RESET_LOCALPLAYER_STATE": "RESET_LOCALPLAYER_STATE",
    "_STOP_ALL_SCREEN_EFFECTS": "ANIMPOSTFX_STOP_ALL",
    "_WORLD3D_TO_SCREEN2D": "GET_SCREEN_COORD_FROM_WORLD_COORD",
    "_IS_VEHICLE_ENGINE_ON": "GET_IS_VEHICLE_ENGINE_RUNNING",
    "_SHOW_CURSOR_THIS_FRAME": "SET_MOUSE_CURSOR_ACTIVE_THIS_FRAME",
    "_GET_THREAD_NAME": "GET_NAME_OF_SCRIPT_WITH_THIS_ID",
    "_0xDADFADA5A20143A8": "SCRIPT_THREAD_ITERATOR_RESET",
    "_0x30B4FA1C82DD4B9F": "SCRIPT_THREAD_ITERATOR_GET_NEXT_THREAD_ID",
    "_PUSH_SCALEFORM_MOVIE_FUNCTION": "BEGIN_SCALEFORM_MOVIE_METHOD",
    "_PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT": "SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT",
    "_POP_SCALEFORM_MOVIE_FUNCTION_VOID": "END_SCALEFORM_MOVIE_METHOD",
    "_ADD_TEXT_COMPONENT_STRING": "ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME",
    "_SET_RADAR_BIGMAP_ENABLED": "SET_RADAR_BIGMAP_ENABLED",
    "_SET_VEHICLE_ENGINE_POWER_MULTIPLIER": "SET_VEHICLE_ENGINE_POWER_MULTIPLIER",
    "_SET_VEHICLE_ENGINE_TORQUE_MULTIPLIER": "SET_VEHICLE_ENGINE_TORQUE_MULTIPLIER",
    # Интерьеры (пункт 9 roadmap): в SDK 2016 года ещё безымянные «prop»-имена.
    "_ENABLE_INTERIOR_PROP": "ACTIVATE_INTERIOR_ENTITY_SET",
    "_DISABLE_INTERIOR_PROP": "DEACTIVATE_INTERIOR_ENTITY_SET",
    "_IS_INTERIOR_PROP_ENABLED": "IS_INTERIOR_ENTITY_SET_ACTIVE",
    "_LOAD_INTERIOR": "PIN_INTERIOR_IN_MEMORY",
    "_LOAD_MP_DLC_MAPS": "ON_ENTER_MP",
}

# Нет в заголовке SDK 2016 года: хэш и сигнатура вручную.
EXTRA = [
    ("void", "ENABLE_DISPATCH_SERVICE", "int dispatchService, BOOL toggle", "0xDC0F817884CDD856"),
    # В SDK 2016 года безымянная _0xF8DEE0A5600CBB93: открывает всю карту (туман сюжета).
    ("void", "SET_MINIMAP_HIDE_FOW", "BOOL toggle", "0xF8DEE0A5600CBB93"),
    # Полоска способности персонажа под мини-картой (в SDK 2016 года её нет).
    ("void", "SET_ABILITY_BAR_VISIBILITY", "BOOL visible", "0x1DFEDD15019315A9"),
]

LINE = re.compile(
    r"static\s+(?P<ret>[\w]+\s*\*?)\s+(?P<name>\w+)\((?P<params>[^)]*)\)\s*\{\s*(?:return\s+)?"
    r"invoke<[^>]+>\((?P<hash>0x[0-9A-Fa-f]+)")


def arg_names(params):
    if not params:
        return []
    return [p.strip().split()[-1].lstrip("*") for p in params.split(",")]


def main(path):
    src = pathlib.Path(path).read_text(encoding="utf-8", errors="replace")
    found = {}
    for m in LINE.finditer(src):
        found.setdefault(m["name"], m)
    out = [
        "// Сгенерировано tools/gen_natives.py — не править руками.",
        "// Хэши — исходные хэши PC; ScriptHookV сам переводит их для 1.0.3889.0.",
        "#pragma once",
        '#include "invoke.h"',
        "",
        "namespace n {",
        "",
    ]
    missing = []
    for name in WANTED:
        m = found.get(name)
        if not m:
            missing.append(name)
            continue
        ret = m["ret"].replace(" ", "").replace("Void", "void")
        params = m["params"].strip()
        args = arg_names(params)
        call = "nv::invoke<%s>(%s%s)" % (ret, m["hash"], "".join(", " + a for a in args))
        body = call + ";" if ret == "void" else "return " + call + ";"
        out.append("inline %s %s(%s) { %s }" % (ret, RENAME.get(name, name).lstrip("_"), params, body))
    for ret, name, params, h in EXTRA:
        call = "nv::invoke<%s>(%s%s)" % (ret, h, "".join(", " + a for a in arg_names(params)))
        out.append("inline %s %s(%s) { %s; }" % (ret, name, params, call))
    out += ["", "} // namespace n", ""]
    if missing:
        sys.exit("нет в заголовке SDK: " + ", ".join(missing))
    target = pathlib.Path(__file__).resolve().parent.parent / "src" / "natives.h"
    target.write_text("\n".join(out), encoding="utf-8")
    print("%d функций -> %s" % (len(WANTED) + len(EXTRA), target))


if __name__ == "__main__":
    main(sys.argv[1])
