# FloV:MP — клиентский ресурс (js-module).
# Чистый client-side: серверной логики нет (она в flovmp-core на C#).
type = "js"
client-main = "client/index.js"
client-files = [
    "client/**/*",
    "client/*",
    "client/html/*",
    "client/html/**/*",
]
